FROM node:22-alpine
ENV TZ=UTC 
WORKDIR /app


COPY ./package*.json /app 

RUN npm install -g npm@latest && npm install -g @angular/cli


COPY . .

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "4200"]